### ISSUE TITLE
object 'ScalesList' not found

### ISSUE THREAD

**Issue by meiqingli** [dlab-berkeley/R-Data-Visualization#31]
Issue running the solutions notebook. 
![Screenshot_1](https://user-images.githubusercontent.com/35152977/191112651-eccd8ce2-aac3-4764-976c-b50f15187d42.jpg)
See screenshot below:

**Comment by asteves** [comment]
This suggests to me that some of the required packages from the workshop are not installed on your computer. I do not reproduce the error on DataHub. 

Can you confirm your sessionInfo() with https://github.com/r-lib/sessioninfo package and then rerun to see if the issue persists?

**Comment by meiqingli** [comment]
Thanks, Alex! I printed out the session info, but not clear about what might be missing from the packages though...
![Screenshot_1](https://user-images.githubusercontent.com/35152977/191136291-201bd9a9-9459-4f20-ab8f-0a257a4c235f.jpg)

**Comment by asteves** [comment]
From reading the session notes, I would confirm the following from a clean session: 

1. You have upgraded to the latest versions of packages and that they are loaded in your session. 
2. You can successfully produce plots A,B,C,D

My sense of this error message is that something in your environment is off because the solutions work fine both on my Mac machine and on DataHub and we have not had previous reports of issues on Windows Machines. If there is an issue we will of course need to update.

**Comment by meiqingli** [comment]
> From reading the session notes, I would confirm the following from a clean session:
> 
> 1. You have upgraded to the latest versions of packages and that they are loaded in your session.
> 2. You can successfully produce plots A,B,C,D
> 
> My sense of this error message is that something in your environment is off because the solutions work fine both on my Mac machine and on DataHub and we have not had previous reports of issues on Windows Machines. If there is an issue we will of course need to update.

Thank you!! I will look into it.
